language: php
php:
  - 5.6
  - 7.0
  
before_script:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction --dev

script:
  - bin/phpspec run -v
  
notifications:
  email: false